# Generated by Django 5.1.4 on 2026-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('unit', models.CharField(max_length=50, verbose_name='Ед. изм.')),
                ('group', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Группа товаров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар каталога',
                'verbose_name_plural': 'Товары каталога',
                'ordering': ['article'],
            },
        ),
    ]
