# Generated by Django 5.1.4 on 2026-04-16 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название сметы')),
                ('original_file', models.FileField(upload_to='estimates/%Y/%m/', verbose_name='Исходный Excel')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('uploaded', 'Загружена'), ('processing', 'В обработке'), ('done', 'Готова'), ('error', 'Ошибка')], default='uploaded', max_length=20)),
                ('mapping_config', models.JSONField(blank=True, default=dict, verbose_name='Маппинг колонок')),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimatePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(default=0, verbose_name='№ строки')),
                ('original_name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('original_article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество')),
                ('material_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена материалов')),
                ('installation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена монтажа')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Уверенность (0.0–1.0)')),
                ('match_type', models.CharField(choices=[('none', 'Не сопоставлено'), ('auto', 'Автоматически'), ('manual', 'Вручную')], default='none', max_length=10, verbose_name='Тип сопоставления')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='projects.estimate')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_positions', to='catalog.product', verbose_name='Товар каталога')),
            ],
            options={
                'verbose_name': 'Позиция сметы',
                'verbose_name_plural': 'Позиции сметы',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project', verbose_name='Проект'),
        ),
    ]
