# Generated by Django 5.1.4 on 2026-04-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='start_column',
            field=models.IntegerField(default=1, verbose_name='Стартовая колонка'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='start_row',
            field=models.IntegerField(default=1, verbose_name='Стартовая строка'),
        ),
    ]
