# Generated by Django 5.1.4 on 2026-04-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_estimate_start_column_estimate_start_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateposition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='estimates/positions/', verbose_name='Фото позиции'),
        ),
    ]
