# Generated by Django 5.1.4 on 2026-04-16 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='pricelists/%Y/%m/', verbose_name='Исходный Excel')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'В обработке'), ('done', 'Готов'), ('error', 'Ошибка')], default='uploaded', max_length=20)),
                ('mapping_config', models.JSONField(blank=True, default=dict, help_text='Пример: {"article": "Колонка A", "name": "Колонка B", "price": "Колонка C"}', verbose_name='Маппинг колонок')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Обработано строк')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelists', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceListPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(default=0, verbose_name='№ строки')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Ед. изм.')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricelist_positions', to='catalog.product', verbose_name='Товар каталога')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='pricelists.pricelist')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Позиции прайса',
                'ordering': ['row_number'],
            },
        ),
    ]
