# Generated by Django 5.1.4 on 2026-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistposition',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. характеристики'),
        ),
    ]
