# Generated by Django 5.1.4 on 2026-04-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0002_pricelistposition_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='start_row',
            field=models.IntegerField(default=1, help_text='Обычно 1. Если перед таблицей есть текст, укажите строку с заголовками колонок.', verbose_name='Стартовая строка (с заголовками)'),
        ),
    ]
