# Generated by Django 5.1.4 on 2026-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0003_pricelist_start_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='start_column',
            field=models.IntegerField(default=1, help_text='Обычно 1 (Колонка A). Если таблица смещена вправо, укажите номер начальной колонки.', verbose_name='Стартовая колонка'),
        ),
        migrations.AddField(
            model_name='pricelistposition',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Валюта'),
        ),
    ]
