# Generated by Django 5.1.4 on 2026-04-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽ Рубль'), ('USD', '$ Доллар'), ('EUR', '€ Евро'), ('CNY', '¥ Юань')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
